// The deck: 48 tricks in four suits of 12, like a Spanish deck, plus card 0.
// Each step has one thing to click, so a set of five tries has a clear pass/fail.
// Adding a trick means adding an entry here; card numbers follow the order.

export const SUITS = [
  { id: 'manners', name: 'Manners', short: 'Manners', blurb: 'The everyday ones: attention, sit, down, stay, come and leave it.' },
  { id: 'poses', name: 'Poses & paws', short: 'Poses', blurb: 'Shake, high five, sit pretty and the rest of the photo ops.' },
  { id: 'moves', name: 'Moves', short: 'Moves', blurb: 'Spins, rolls, crawls, jumps and weaves.' },
  { id: 'helpers', name: 'Helpers & games', short: 'Helpers', blurb: 'Fetch, tidying up, the vet trick and nose games.' },
];

export const LEVELS = ['', 'First week', 'Easy', 'Tricky', 'Show-stopper'];

export const METHODS = {
  pair: { name: 'Pairing', about: 'Click, then treat, with nothing asked of your dog. It teaches what the click means.' },
  lure: { name: 'Lure', about: 'Your dog follows a treat in your hand into position. Then the treat disappears and your hand movement becomes the signal.' },
  shape: { name: 'Shape', about: 'Click small steps toward the finished trick, raising the bar a little at a time.' },
  capture: { name: 'Capture', about: 'Wait for your dog to do it on their own, click, and treat. Then name it.' },
  target: { name: 'Target', about: 'Your dog touches something with their nose or paw. Moving the target moves the dog.' },
};

const T = [
  {
    id: 'charge', suit: 'start', level: 1, emoji: '⚡', name: 'Charge the clicker', method: 'pair',
    blurb: 'Teach your dog that the click means a treat is coming. Every other card builds on this one.',
    steps: [
      { do: 'Click, then treat', click: 'Click anytime. Your dog doesn’t have to do anything.',
        tip: 'Click once, then hand over a treat within a second or two. Keep your treat hand still until after the click, so the click predicts food and your hand doesn’t.' },
      { do: 'Click from different spots', click: 'Click while your dog is sniffing or looking away.',
        tip: 'Move around and vary the timing. Ten to twenty pairings over a couple of short sessions is plenty.' },
      { do: 'Check it works', click: 'Click when your dog isn’t looking at you.',
        tip: 'If their head whips round toward you, the clicker is charged. From now on a click always means a treat, even one you didn’t mean.' },
    ],
    fix: [
      'Your dog flinches at the click: switch to the Soft sound in Settings, or muffle a real clicker in a pocket.',
      'Your dog stares at your treat hand: keep treats in a pouch behind your back and only reach after the click.',
    ],
  },

  // Manners
  {
    id: 'name', suit: 'manners', level: 1, emoji: '📛', name: 'Name game', method: 'capture',
    blurb: 'Your dog turns to look at you when they hear their name.',
    why: 'Attention first. Every recall and every trick starts with a dog who’s listening.',
    cue: { word: 'their name' },
    steps: [
      { do: 'Say it, reward it', click: 'Click as they turn toward you after you say their name.',
        tip: 'Start in a quiet room, close by. Say the name once in a happy voice. Don’t repeat it.' },
      { do: 'Name while they’re busy', click: 'Click when they look up from a sniff or a toy.',
        tip: 'Wait until they’re a little distracted, not glued to something.' },
      { do: 'Name from another room', click: 'Click when they come to find you.',
        tip: 'Step out of sight and say the name once. Give several treats in a row the first few times.' },
    ],
    fix: [
      'No head turn: move closer, cut the distractions, and use a higher, happier voice.',
      'Their name has been used when they’re in trouble: pick a fresh attention word like “Look!” that has only ever meant good things.',
    ],
  },
  {
    id: 'sit', suit: 'manners', level: 1, emoji: '🪑', name: 'Sit', method: 'lure', hold: true,
    blurb: 'Bottom on the floor, and it stays there until you say so.',
    cue: { word: 'Sit', signal: 'Palm up, lift your hand from waist to chest.' },
    steps: [
      { do: 'Lure up and back', click: 'Click the moment their bottom touches the floor.',
        tip: 'Hold a treat at their nose and move it slowly up and back over their head. As the head goes up, the bottom goes down. No pushing.' },
      { do: 'Empty hand', click: 'Click a sit that follows your empty hand.',
        tip: 'Make the same motion with no treat in that hand, and treat from your other hand after the click.' },
      { do: 'Smaller signal', click: 'Click a sit to a small upward flick of your palm.',
        tip: 'Shrink the motion a little each set until it’s a small lift of the hand.' },
      { do: 'Add the word', click: 'Click a sit after the word alone.',
        tip: 'Say “Sit” once, pause a second, then give the hand signal. Soon they’ll sit before your hand moves.' },
    ],
    fix: [
      'They jump up at the treat: hold it lower, right at the nose, and move slower.',
      'They back up instead of sitting: practice with their back to a wall or in a corner.',
    ],
  },
  {
    id: 'down', suit: 'manners', level: 1, emoji: '🥞', name: 'Down', method: 'lure', hold: true, needs: ['sit'],
    blurb: 'Lie down, elbows on the floor, flat as a pancake.',
    cue: { word: 'Down', signal: 'Flat palm, lower it toward the floor.' },
    steps: [
      { do: 'Nose to the floor', click: 'Click when the elbows touch the ground.',
        tip: 'From a sit, hold a treat at their nose and lower it straight down between their front paws, then slowly out along the floor.' },
      { do: 'Empty hand', click: 'Click a down that follows your empty hand.',
        tip: 'Same motion without food in the luring hand. Treat from your other hand.' },
      { do: 'Stand up straighter', click: 'Click a down while you bend less.',
        tip: 'Bend a little less each set until you can signal from standing.' },
      { do: 'Add the word', click: 'Click a down on the word alone.',
        tip: 'Say “Down” once, pause, then signal.' },
    ],
    fix: [
      'They stand up and follow the treat: move it more slowly, and bring it in toward their chest before going forward.',
      'Stuck halfway: click the elbows dipping, then ask for a little more.',
      'Use “Off” for getting off the couch, so “Down” only ever means lie down.',
    ],
  },
  {
    id: 'touch', suit: 'manners', level: 1, emoji: '👆', name: 'Touch', method: 'target',
    blurb: 'Nose to your palm. The easiest way to move your dog without grabbing them.',
    why: 'Call them off the couch, onto the scale at the vet, or back to you on a walk.',
    cue: { word: 'Touch', signal: 'Flat palm toward your dog, fingers down.' },
    steps: [
      { do: 'Offer your palm', click: 'Click when their nose bumps your flat hand.',
        tip: 'Hold your palm a few inches from their nose. Most dogs sniff it. Click the bump, treat from the other hand, and take the hand away between tries.' },
      { do: 'Move the hand', click: 'Click a touch when your hand is to the side, high or low.',
        tip: 'Change where you hold it so they learn to go to the hand, not to one spot.' },
      { do: 'Make them walk to it', click: 'Click a touch from a step or two away.',
        tip: 'Offer your hand a little further off so they have to move to reach it.' },
      { do: 'Add the word', click: 'Click a touch after the word.',
        tip: 'Say “Touch” just before you present your hand.' },
    ],
    fix: [
      'They lick or mouth your hand: click earlier, the moment the nose arrives.',
      'They ignore your hand: rub a treat on your palm first.',
    ],
  },
  {
    id: 'leave', suit: 'manners', level: 1, emoji: '🚫', name: 'Leave it', method: 'shape',
    blurb: 'Your dog backs off whatever you point at, and looks to you instead.',
    why: 'The one that keeps chicken bones and dropped pills out of their mouth.',
    cue: { word: 'Leave it', signal: 'Point at the thing, then close your hand.' },
    steps: [
      { do: 'Closed fist', click: 'Click the moment their nose moves away from your closed hand.',
        tip: 'Hold a treat in a closed fist. Let them sniff, lick and paw, and say nothing. When they pull back, click and treat from your other hand, never the one they’re leaving.' },
      { do: 'Open hand', click: 'Click when they stay off a treat on your open palm.',
        tip: 'Open your hand slowly. If they go for it, close it again.' },
      { do: 'Treat on the floor', click: 'Click for looking away from a treat on the floor.',
        tip: 'Put a treat down and cover it with your foot if they dive for it.' },
      { do: 'Add the word', click: 'Click when they leave it after the word.',
        tip: 'Say “Leave it” as you put the treat down. Then try toys, dropped food, and things on walks.' },
    ],
    fix: [
      'They keep pawing at your fist: that’s fine, wait it out and click the smallest pull back.',
      'Walks are too hard: practice with the tempting thing further away.',
    ],
  },
  {
    id: 'drop', suit: 'manners', level: 1, emoji: '🧦', name: 'Drop it', method: 'lure',
    blurb: 'Let go of whatever is in their mouth.',
    why: 'A dog who lets go on cue is a dog you never wrestle a sock from.',
    cue: { word: 'Drop it', signal: 'Open hand under their chin.' },
    steps: [
      { do: 'Trade for a treat', click: 'Click as the toy leaves their mouth.',
        tip: 'While they hold a so-so toy, put a great treat right at their nose. When they let go to eat it, click. Then give the toy back, so letting go never means losing the fun.' },
      { do: 'Say it first', click: 'Click when they let go after the word.',
        tip: 'Say “Drop it”, then show the treat. Hold the toy still and don’t pull.' },
      { do: 'Word before the treat shows', click: 'Click a drop before you reach for a treat.',
        tip: 'Say “Drop it” and wait with your hands still. Reach for the treat only after the click.' },
      { do: 'Favorite toys', click: 'Click a drop of a favorite toy.',
        tip: 'Work up to the good stuff, and bring your best treats.' },
    ],
    fix: [
      'They run off with it: practice in a small room, and give the toy back more often.',
      'Tug games make it hard: stop moving the toy completely. A still toy is boring.',
    ],
  },
  {
    id: 'come', suit: 'manners', level: 2, emoji: '🧲', name: 'Come', method: 'lure', needs: ['name'],
    blurb: 'Stop what they’re doing and run to you.',
    why: 'The trick that could save their life.',
    cue: { word: 'Come', signal: 'Open both arms wide, then bring your hands to your chest.' },
    steps: [
      { do: 'Tiny recalls', click: 'Click as they turn toward you after “Come”.',
        tip: 'Indoors, a few steps apart. Say “Come” once, happily, and back away a step. Click as they turn, and treat when they reach you. Best treats only.' },
      { do: 'Room to room', click: 'Click when they arrive from another room.',
        tip: 'Call once from another room and make a party when they get to you.' },
      { do: 'Outside on a long line', click: 'Click as they turn toward you away from a smell.',
        tip: 'Use a 15–30 ft leash in a yard or park. Call when they’re only mildly interested in something.' },
      { do: 'Hard mode', click: 'Click a recall away from something they like.',
        tip: 'Call away from other dogs or a squirrel only once the easy steps are solid. Call, treat, and send them back to play, so coming to you doesn’t mean the fun ends.' },
    ],
    fix: [
      'They slow down near you: treat at your feet, and hold their collar gently while you treat so it’s never a trick.',
      'Never call them for something they dislike, like a bath or a nail trim. Go and get them instead.',
      'If “Come” has been used a hundred times with no reward, pick a new word like “Here!”',
    ],
  },
  {
    id: 'stay', suit: 'manners', level: 2, emoji: '🗿', name: 'Stay', method: 'shape', hold: true, needs: ['sit'],
    blurb: 'Hold still until you come back and say it’s over.',
    cue: { word: 'Stay', signal: 'Flat palm toward their face, like a stop sign.' },
    steps: [
      { do: 'One second', click: 'Click while they’re still sitting, after one second.',
        tip: 'Ask for a sit, say “Stay” with your palm out, wait one second, click and treat. Then say “Okay!” and step away so they get up.' },
      { do: 'Longer', click: 'Click after 5, then 10, then 20 seconds of stillness.',
        tip: 'Build time before distance, and mix it up: 3 s, 8 s, 2 s, 12 s.' },
      { do: 'One step back', click: 'Click when they stay while you step back and return.',
        tip: 'Step back, step back in, click, treat. Always go back to them to treat instead of calling them to you.' },
      { do: 'Further, and moving', click: 'Click a stay while you walk around them or across the room.',
        tip: 'Add one step at a time. If they get up, you went too far too fast, so make the next one easier.' },
    ],
    fix: [
      'They get up as you move: make the move smaller. Lean back instead of stepping.',
      'Teach a release word (“Okay” or “Free”) so they know exactly when the stay is over.',
    ],
  },
  {
    id: 'wait', suit: 'manners', level: 2, emoji: '⏸️', name: 'Wait at the door', method: 'shape', hold: true, needs: ['sit'],
    blurb: 'Pause at open doors and gates until you say go.',
    why: 'Keeps them from shooting out the front door, or out of the car into traffic.',
    cue: { word: 'Wait', signal: 'Flat palm toward them.' },
    steps: [
      { do: 'Hand on the handle', click: 'Click while they stay sitting as you touch the handle.',
        tip: 'Ask for a sit at the door and touch the handle. If they get up, take your hand away and start again.' },
      { do: 'Crack it open', click: 'Click when they hold the sit while the door opens an inch.',
        tip: 'If they move, the door closes. No scolding; the door does the teaching.' },
      { do: 'Wide open', click: 'Click for staying put with the door wide open.',
        tip: 'Treat them where they sit, inside. Then say “Okay” and walk through together.' },
      { do: 'Car and gate', click: 'Click a wait at the car door or the gate.',
        tip: 'Practice at each door you use, one at a time, with a leash on.' },
    ],
    fix: [
      'They bolt: keep a leash on for practice until it’s solid.',
      'Wait and Stay are different. Wait means pause until the next thing. Stay means don’t move until I come back.',
    ],
  },
  {
    id: 'place', suit: 'manners', level: 2, emoji: '🛏️', name: 'Go to your bed', method: 'shape', hold: true,
    blurb: 'Go to a bed or mat and lie down on it.',
    why: 'Somewhere to be when the doorbell rings or dinner is on the table.',
    cue: { word: 'Bed', signal: 'Point to the bed.' },
    steps: [
      { do: 'Anything on the bed', click: 'Click one paw on the bed or mat.',
        tip: 'Stand near the mat and click any interest: a look, a sniff, a paw. Toss the treat off the mat so they have to come back.' },
      { do: 'All four paws', click: 'Click when all four paws are on the mat.',
        tip: 'Once they’re stepping on it every time, wait for more.' },
      { do: 'Lie down on it', click: 'Click a down on the mat.',
        tip: 'Ask for a down a few times, then wait for them to offer it.' },
      { do: 'Send from a distance', click: 'Click when they go to the mat from a few steps away.',
        tip: 'Point and say “Bed”. Stand one step further back each set.' },
      { do: 'Stay there', click: 'Click calm lying on the mat, for longer and longer.',
        tip: 'Drop treats between their paws while they lie there. Release with “Okay”.' },
    ],
    fix: [
      'They only sit on it: click one step earlier, then wait longer for the down.',
      'Use a mat you can carry. Once they know it, it goes to cafés and friends’ houses too.',
    ],
  },
  {
    id: 'speak', suit: 'helpers', level: 2, emoji: '🗣️', name: 'Speak', method: 'capture',
    blurb: 'One woof on cue.',
    cue: { word: 'Speak', signal: 'Open and close your hand like a mouth.' },
    steps: [
      { do: 'Catch a bark', click: 'Click a bark.',
        tip: 'Find what gets a bark: a knock, a toy held just out of reach, the leash coming out. Click the bark.' },
      { do: 'Just one', click: 'Click a single bark.',
        tip: 'Click the first bark, not the tenth.' },
      { do: 'Add the word', click: 'Click a bark after the word.',
        tip: 'Say “Speak” just before you do the thing that sets it off.' },
      { do: 'Word alone', click: 'Click a bark to the word only.',
        tip: 'Say “Speak” and wait. Stop clicking barks you didn’t ask for.' },
    ],
    fix: [
      'You’re getting more barking than you wanted: teach Quiet next, and never reward barks you didn’t ask for.',
    ],
  },
  {
    id: 'quiet', suit: 'manners', level: 2, emoji: '🤫', name: 'Quiet', method: 'capture', needs: ['speak'],
    blurb: 'Stop barking when you ask.',
    cue: { word: 'Quiet', signal: 'Finger to your lips.' },
    steps: [
      { do: 'Wait for the gap', click: 'Click the first second of silence after a bark.',
        tip: 'Cue Speak. When they pause for breath, click and treat.' },
      { do: 'Longer quiet', click: 'Click 3, then 5 seconds of silence.',
        tip: 'Count in your head. Start the count again if they bark.' },
      { do: 'Add the word', click: 'Click silence after “Quiet”.',
        tip: 'Say “Quiet” once, calmly, just as the barking pauses.' },
      { do: 'Real life', click: 'Click quiet after a knock at the door.',
        tip: 'Get a friend to knock. Keep your voice low; shouting just sounds like barking along.' },
    ],
    fix: [
      'They bark at you for the treat: wait for longer silences before clicking.',
    ],
  },
  {
    id: 'settle', suit: 'manners', level: 3, emoji: '😌', name: 'Settle', method: 'capture', hold: true, needs: ['place', 'down'],
    blurb: 'Lie down and properly relax, not just wait for the next treat.',
    why: 'An off switch for busy dogs, at home or at a café.',
    cue: { word: 'Settle' },
    steps: [
      { do: 'Catch it happening', click: 'Click when they lie down and relax on their own.',
        tip: 'Sit with a book. When they lie down, quietly place a treat between their paws. If the click gets them up, skip it and just place the treat.' },
      { do: 'Reward the flop', click: 'Click a roll onto one hip, or chin on the floor.',
        tip: 'Relaxed signs: rolling onto a hip, a sigh, chin down, soft eyes.' },
      { do: 'Longer and longer', click: 'Click calm after a minute, then five.',
        tip: 'Space the treats out further as they relax more.' },
      { do: 'Add the word', click: 'Click a settle after the word.',
        tip: 'Say “Settle” softly as they start to lie down.' },
    ],
    fix: [
      'They pop up for every treat: use boring treats (their kibble) and hand them over slowly.',
      'They’re too wound up: practice after a walk, not before.',
    ],
  },

  // Poses & paws
  {
    id: 'shake', suit: 'poses', level: 1, emoji: '🤝', name: 'Shake', method: 'lure', needs: ['sit'],
    blurb: 'Put a paw in your hand.',
    cue: { word: 'Shake', signal: 'Open hand, palm up, below their chin.' },
    steps: [
      { do: 'Treat in a fist', click: 'Click when a paw lifts toward your fist.',
        tip: 'Ask for a sit. Hold a treat in a closed fist at chest height. Most dogs paw at it. Click the paw lifting, even a little.' },
      { do: 'Paw to the fist', click: 'Click when the paw touches your fist.',
        tip: 'Now wait for contact before you click.' },
      { do: 'Open hand', click: 'Click a paw placed in your open palm.',
        tip: 'Hold out an empty flat hand below their chin. Treat from the other hand.' },
      { do: 'Add the word', click: 'Click a shake after the word.',
        tip: 'Say “Shake”, then offer your hand.' },
    ],
    fix: [
      'They sniff instead of pawing: lower your fist to the floor and wait.',
      'They use either paw: pick one and click only that one. The other paw can have its own cue later.',
    ],
  },
  {
    id: 'bow', suit: 'poses', level: 2, emoji: '🎭', name: 'Take a bow', method: 'lure', hold: true,
    blurb: 'Front end down, back end up, like a play bow.',
    cue: { word: 'Take a bow', signal: 'Sweep one hand down to the floor.' },
    steps: [
      { do: 'Lure down from a stand', click: 'Click the chest dipping while the rear stays up.',
        tip: 'With them standing, bring a treat from the nose down to the floor, close to the chest. Click as the front drops, before the back end follows.' },
      { do: 'Arm under the belly', click: 'Click a bow with your arm resting under their belly.',
        tip: 'If the rear keeps dropping, rest your other arm under their belly as a reminder. No lifting.' },
      { do: 'Catch the stretch', click: 'Click the morning stretch.',
        tip: 'Most dogs bow when they wake up or want to play. Click it and treat.' },
      { do: 'Add the word', click: 'Click a bow after the words.',
        tip: 'Say “Take a bow”, then the signal.' },
    ],
    fix: ['They lie down: click sooner, the instant the chest dips.'],
  },
  {
    id: 'pawsup', suit: 'poses', level: 2, emoji: '📦', name: 'Paws up', method: 'shape', hold: true,
    blurb: 'Front feet up on a step, a box, or a log.',
    why: 'Great for photos, and half of Say your prayers.',
    cue: { word: 'Paws up', signal: 'Pat the object.' },
    steps: [
      { do: 'One paw on', click: 'Click one front paw on the box or step.',
        tip: 'Use a low step or a sturdy box that won’t tip. Lure over it if you need to.' },
      { do: 'Both front paws', click: 'Click both front paws on the box.',
        tip: 'Toss the treat off the box to reset each time.' },
      { do: 'Hold it', click: 'Click after 2, then 5 seconds with paws up.',
        tip: 'Treat while they’re still up there.' },
      { do: 'Add the word', click: 'Click paws up after the word.',
        tip: 'Say “Paws up” and point. Then try a bench, a log, your knee.' },
    ],
    fix: [
      'They climb all the way on: use something narrower than their body.',
      'Keep it low for puppies.',
    ],
  },
  {
    id: 'headdown', suit: 'poses', level: 2, emoji: '😴', name: 'Are you tired?', method: 'lure', hold: true, needs: ['down'],
    blurb: 'Chin flat on the floor between the paws.',
    cue: { word: 'Are you tired?', signal: 'Point at the floor between their paws.' },
    steps: [
      { do: 'Chin to the floor', click: 'Click the chin touching the floor.',
        tip: 'From a down, bring a treat to the floor right between their paws. Click the chin landing.' },
      { do: 'Hold it', click: 'Click after 1, then 3 seconds with chin down.',
        tip: 'Deliver the treat at floor level so the chin stays put.' },
      { do: 'Empty hand', click: 'Click chin down to a finger pointing at the floor.',
        tip: 'Same motion, no treat, then shrink it to a point.' },
      { do: 'Add the words', click: 'Click chin down after the words.',
        tip: '“Are you tired?” gets a laugh every time.' },
    ],
    fix: ['They lift the head to take the treat: bring it all the way down to them.'],
  },
  {
    id: 'highfive', suit: 'poses', level: 2, emoji: '✋', name: 'High five', method: 'shape', needs: ['shake'],
    blurb: 'Paw to your raised palm.',
    cue: { word: 'High five', signal: 'Palm facing them at nose height.' },
    steps: [
      { do: 'Shake, then tilt', click: 'Click a paw on your hand tilted up a little.',
        tip: 'Ask for Shake. Each set, tilt your palm a little more upright.' },
      { do: 'Palm facing them', click: 'Click a paw pressed to your upright palm.',
        tip: 'Hold your hand up like a high five at shoulder height.' },
      { do: 'A bit higher', click: 'Click a paw on a hand a little higher.',
        tip: 'Never higher than their nose. Keep sets short; it’s work for the shoulders.' },
      { do: 'Add the words', click: 'Click a high five after the words.',
        tip: 'Say “High five!”, then raise your hand.' },
    ],
    fix: ['They go back to Shake: change the angle more gradually.'],
  },
  {
    id: 'pawtarget', suit: 'poses', level: 2, emoji: '🐾', name: 'Paw target', method: 'target', needs: ['shake'],
    blurb: 'Press a sticky note with a front paw.',
    why: 'The building block for closing doors and Cover your eyes.',
    cue: { word: 'Press', signal: 'Point to the note.' },
    steps: [
      { do: 'Note on the floor', click: 'Click any paw on the sticky note.',
        tip: 'Put a sticky note on the floor. Click a look, then a step near it, then a paw on it. Toss the treat away to reset.' },
      { do: 'On purpose', click: 'Click a clear paw press on the note.',
        tip: 'Wait for a deliberate press, not a walk across it.' },
      { do: 'Move it around', click: 'Click a press on the note in a new spot.',
        tip: 'Floor, low wall, the side of a box. Then smaller notes.' },
      { do: 'Add the word', click: 'Click a press after the word.',
        tip: 'Say “Press” as they head toward the note.' },
    ],
    fix: ['They nose it instead: hold a treat low on the far side so the paw comes up first.'],
  },
  {
    id: 'wave', suit: 'poses', level: 3, emoji: '👋', name: 'Wave', method: 'shape', needs: ['highfive'],
    blurb: 'A paw raised and waved in the air. Good for hellos and goodbyes.',
    cue: { word: 'Say bye', signal: 'Wave your hand.' },
    steps: [
      { do: 'Pull your hand away', click: 'Click the paw in the air as your hand moves back.',
        tip: 'Cue High five, then pull your hand away just before the paw lands. Click the paw in the air.' },
      { do: 'Out of reach', click: 'Click a paw lift toward a hand a foot away.',
        tip: 'Hold your hand high and out of reach.' },
      { do: 'Wave instead', click: 'Click a paw lift to your waving hand.',
        tip: 'Turn the high-five hand into a small wave.' },
      { do: 'Add the words', click: 'Click a wave after the words.',
        tip: 'Say “Say bye!” or “Wave”, then the hand signal.' },
    ],
    fix: ['They reach out and touch you anyway: step back so your hand is further off.'],
  },
  {
    id: 'sitpretty', suit: 'poses', level: 3, emoji: '🐿️', name: 'Sit pretty', method: 'lure', hold: true, needs: ['sit'],
    blurb: 'Sit back on the haunches with both front paws up. Some call it Beg.',
    caution: 'This takes core strength. Skip it for puppies under a year, and check with your vet first for long-backed breeds or any dog with back or hip trouble.',
    cue: { word: 'Sit pretty', signal: 'Raise a flat hand above their head.' },
    steps: [
      { do: 'One paw up', click: 'Click a front paw lifting from a sit.',
        tip: 'From a sit, move a treat slowly up and a little back from the nose. Click the first paw leaving the floor.' },
      { do: 'Both paws up', click: 'Click both front paws off the floor.',
        tip: 'If they wobble, sit them in a corner so the walls help.' },
      { do: 'Hold it', click: 'Click after 1, then 3 seconds up.',
        tip: 'Keep the treat close to the nose. Short sets; it’s a workout.' },
      { do: 'Add the words', click: 'Click sit pretty after the words.',
        tip: 'Say “Sit pretty”, then lift your hand.' },
    ],
    fix: ['They stand on their back legs: the treat is too high. Keep it at nose level.'],
  },
  {
    id: 'scratch', suit: 'poses', level: 3, emoji: '💅', name: 'Scratch board', method: 'shape', needs: ['shake'],
    blurb: 'Your dog files their own front nails on a sandpaper board.',
    why: 'Nail trims without the wrestling.',
    caution: 'Check their paw pads for scuffs, and stop if the board seems too rough. Back nails still need trimming.',
    cue: { word: 'Scratch', signal: 'Tap the board.' },
    steps: [
      { do: 'Paw on the board', click: 'Click a paw on the board.',
        tip: 'Glue 80–100 grit sandpaper or skateboard grip tape to a board. Lay it flat and click any paw touch.' },
      { do: 'A scrape', click: 'Click a paw dragging down the board.',
        tip: 'Hold a treat just under the far edge. Most dogs dig at it. Click the scrape.' },
      { do: 'Tilt it up', click: 'Click a scratch with the board at an angle.',
        tip: 'About 45° works well. Hold it steady against your leg.' },
      { do: 'More strokes', click: 'Click after two, then three scratches.',
        tip: 'A few sessions a week keeps the front nails short.' },
    ],
    fix: ['They only use one paw: that’s normal. Teach the other paw with its own cue if you like.'],
  },
  {
    id: 'covereyes', suit: 'poses', level: 4, emoji: '🙈', name: 'Cover your eyes', method: 'shape', hold: true, needs: ['shake'],
    blurb: 'A paw over the nose, like they’re embarrassed.',
    cue: { word: 'Shy', signal: 'Touch your own nose.' },
    steps: [
      { do: 'Tape on the muzzle', click: 'Click any paw swipe at the tape.',
        tip: 'Stick a small piece of low-tack painter’s tape lightly on top of the muzzle. Most dogs paw at it. If yours seems worried, skip this and use a paw target held near the face.' },
      { do: 'Paw to the face', click: 'Click a paw moving up to the face.',
        tip: 'Try without the tape. If nothing happens, put it back for one set.' },
      { do: 'Hold it', click: 'Click when the paw rests over the nose for a moment.',
        tip: 'Wait a beat longer before clicking each set.' },
      { do: 'Add the word', click: 'Click a paw over the face after the word.',
        tip: 'Say “Shy” or “Are you embarrassed?”' },
    ],
    fix: ['They rub their face on the floor: a good guess, but only click paw movement.'],
  },
  {
    id: 'prayers', suit: 'poses', level: 4, emoji: '🙏', name: 'Say your prayers', method: 'lure', hold: true, needs: ['pawsup', 'headdown'],
    blurb: 'Paws up on a chair, head tucked down between them.',
    cue: { word: 'Say your prayers', signal: 'Bow your head.' },
    steps: [
      { do: 'Paws up on a chair', click: 'Click both front paws on the seat.',
        tip: 'Use a stool or low chair at about chest height.' },
      { do: 'Head down', click: 'Click the head dipping between the paws.',
        tip: 'Hold a treat just under the edge of the seat, between their legs.' },
      { do: 'Hold it', click: 'Click after 1, then 3 seconds with head tucked.',
        tip: 'Deliver the treat down low so the head stays there.' },
      { do: 'Add the words', click: 'Click prayers after the words.',
        tip: 'Say “Say your prayers”, then point to the seat.' },
    ],
    fix: ['They pop up for the treat: bring the treat to them in the tucked spot.'],
  },
  {
    id: 'balance', suit: 'poses', level: 4, emoji: '🍪', name: 'Treat on the nose', method: 'shape', hold: true, needs: ['stay', 'leave'],
    blurb: 'Balance a treat on the nose until you say okay.',
    cue: { word: 'Leave it… Okay!' },
    steps: [
      { do: 'Hand under the chin', click: 'Click holding still with your hand cupping their chin.',
        tip: 'From a sit, cup their chin gently. Click stillness.' },
      { do: 'Treat touches the nose', click: 'Click stillness with a treat touching the top of the nose.',
        tip: 'Rest a flat treat on the muzzle for a split second, click, take it away, and give it.' },
      { do: 'Let go', click: 'Click after one second balancing on their own.',
        tip: 'Say “Leave it” and take your hands away. Add seconds slowly.' },
      { do: 'Okay!', click: 'Click the grab on “Okay”.',
        tip: 'Say “Okay” and let them flip it or drop it and eat it. The catch comes with practice.' },
    ],
    fix: ['They snatch it early: go back a step, and use a less exciting treat.'],
  },

  // Moves
  {
    id: 'spin', suit: 'moves', level: 1, emoji: '🌀', name: 'Spin', method: 'lure',
    blurb: 'A full circle in place.',
    cue: { word: 'Spin', signal: 'Draw a small circle with your finger.' },
    steps: [
      { do: 'Quarter turn', click: 'Click when they follow the treat a quarter circle.',
        tip: 'Treat at nose level. Move it slowly out to the side in a wide circle.' },
      { do: 'Full circle', click: 'Click a full circle.',
        tip: 'Keep the lure at nose height, wide enough that they don’t have to twist.' },
      { do: 'Empty hand', click: 'Click a spin to an empty-hand circle.',
        tip: 'Same motion, no treat. Treat from the other hand.' },
      { do: 'Smaller signal', click: 'Click a spin to a small finger circle.',
        tip: 'Make the circle smaller each set.' },
      { do: 'Add the word', click: 'Click a spin after the word.',
        tip: 'Say “Spin”, pause, then signal.' },
    ],
    fix: ['They sit instead: keep the lure lower and move it a bit faster at first.'],
  },
  {
    id: 'backup', suit: 'moves', level: 2, emoji: '⏪', name: 'Back up', method: 'shape',
    blurb: 'Walk straight backward.',
    why: 'Clears the doorway or the kitchen without shoving.',
    cue: { word: 'Back', signal: 'Push both palms toward them.' },
    steps: [
      { do: 'Use a hallway', click: 'Click any step backward.',
        tip: 'Face your dog in a narrow hallway or between the couch and a wall. Step slowly into them. Click any weight shift back, and toss the treat behind them.' },
      { do: 'Two or three steps', click: 'Click two, then three steps back.',
        tip: 'Walk toward them a little further each time.' },
      { do: 'You stand still', click: 'Click backing up while you stay put.',
        tip: 'Shuffle one foot forward instead of stepping.' },
      { do: 'Add the word', click: 'Click a back up after the word.',
        tip: 'Say “Back”.' },
    ],
    fix: ['They turn around: use a narrower space.'],
  },
  {
    id: 'twirl', suit: 'moves', level: 2, emoji: '🌪️', name: 'Twirl', method: 'lure', needs: ['spin'],
    blurb: 'Spin the other way, with its own word.',
    cue: { word: 'Twirl', signal: 'Circle your finger the other way.' },
    steps: [
      { do: 'The other way', click: 'Click a quarter turn in the new direction.',
        tip: 'Lure the opposite way from Spin. Most dogs have a favorite side, so this one’s harder.' },
      { do: 'Full circle', click: 'Click a full circle the other way.',
        tip: 'Go slowly and keep the circle wide.' },
      { do: 'Small signal', click: 'Click a twirl to a small finger circle.',
        tip: 'Fade the lure the same way you did for Spin.' },
      { do: 'Add the word', click: 'Click a twirl after “Twirl”.',
        tip: 'Mix Spin and Twirl only once each one is solid on its own.' },
    ],
    fix: ['They spin their usual way: go back to a quarter turn and move the lure slower.'],
  },
  {
    id: 'middle', suit: 'moves', level: 2, emoji: '🦵', name: 'Middle', method: 'lure', hold: true, needs: ['touch'],
    blurb: 'Stand between your legs, facing forward.',
    why: 'A safe spot when a strange dog or a crowd gets too close.',
    cue: { word: 'Middle', signal: 'Pat both thighs.' },
    steps: [
      { do: 'Lure through', click: 'Click when they stand between your feet, facing forward.',
        tip: 'Stand with feet apart. Lure them around behind you and through, so they end up facing the same way you do.' },
      { do: 'Use Touch', click: 'Click them arriving in the middle to a hand target.',
        tip: 'Hold a Touch hand low in front of your legs instead of a treat.' },
      { do: 'Stay in the middle', click: 'Click after a few seconds in place.',
        tip: 'Treat low, between your knees.' },
      { do: 'Add the word', click: 'Click them finding the middle on the word.',
        tip: 'Say “Middle”, then pat your legs.' },
    ],
    fix: ['Big dogs: stand with feet wide. Small dogs: this might be a crouch.'],
  },
  {
    id: 'jump', suit: 'moves', level: 2, emoji: '🦘', name: 'Jump over', method: 'lure',
    blurb: 'Hop over a bar, your arm, or your leg.',
    caution: 'Keep bars at elbow height or lower. No real jumping for puppies until their growth plates close, roughly 12–18 months, later for giant breeds.',
    cue: { word: 'Over', signal: 'Sweep your arm over the bar.' },
    steps: [
      { do: 'Step over a pole', click: 'Click as they step over a pole on the floor.',
        tip: 'Lay a broom handle flat on the floor and lure them over it.' },
      { do: 'Raise it a little', click: 'Click a hop over a pole a few inches up.',
        tip: 'Rest the ends on books.' },
      { do: 'Over your leg', click: 'Click a jump over your leg.',
        tip: 'Sit on the floor with your leg out and your foot against a wall, so they can’t go round.' },
      { do: 'Add the word', click: 'Click a jump after the word.',
        tip: 'Say “Over”.' },
    ],
    fix: ['They go around: put the bar in a doorway so there’s no way round.'],
  },
  {
    id: 'around', suit: 'moves', level: 2, emoji: '🌳', name: 'Around', method: 'lure', needs: ['touch'],
    blurb: 'Circle a tree, a cone or a chair leg and come back.',
    why: 'A start on agility handling, and a way to burn energy indoors on a rainy day.',
    cue: { word: 'Around', signal: 'Point to the far side of the object.' },
    steps: [
      { do: 'Lure around the post', click: 'Click as they pass behind the chair leg or cone.',
        tip: 'Stand right next to it and lure them round in a tight circle back to you.' },
      { do: 'Empty hand', click: 'Click going around to your pointing hand.',
        tip: 'Point, and treat from the other hand when they come back.' },
      { do: 'Step back', click: 'Click going around when you stand a step away.',
        tip: 'One step further from the post each set. Toss the treat to them on the way back.' },
      { do: 'Add the word', click: 'Click an around on the word.',
        tip: 'Say “Around”. Then try trees, bins and people.' },
    ],
    fix: ['They cut the corner: use something wider, like a laundry basket.'],
  },
  {
    id: 'rollover', suit: 'moves', level: 3, emoji: '🔄', name: 'Roll over', method: 'lure', needs: ['down'],
    blurb: 'All the way over, from one side to the other.',
    caution: 'Use a rug or grass, not a hard floor. If lying on their back seems to worry your dog, stop at the side and teach Play dead instead.',
    cue: { word: 'Roll over', signal: 'Roll your hand in a small circle near the floor.' },
    steps: [
      { do: 'Onto a hip', click: 'Click when they tip onto one hip.',
        tip: 'From a down, move a treat from the nose back toward their shoulder.' },
      { do: 'Onto their side', click: 'Click when they lie flat on their side.',
        tip: 'Keep moving the treat round toward the backbone.' },
      { do: 'Over the top', click: 'Click as they roll onto their back and over.',
        tip: 'Keep the lure moving over the back so gravity helps.' },
      { do: 'Empty hand', click: 'Click a roll to an empty-hand circle.',
        tip: 'Same motion, no treat, then make it smaller.' },
      { do: 'Add the words', click: 'Click a roll over after the words.',
        tip: 'Say “Roll over”, then signal.' },
    ],
    fix: ['They get up: the treat moved too fast or too high.'],
  },
  {
    id: 'bang', suit: 'moves', level: 3, emoji: '💥', name: 'Play dead', method: 'lure', hold: true, needs: ['down'],
    blurb: 'Flop over on “Bang!” and lie still.',
    cue: { word: 'Bang!', signal: 'Finger gun.' },
    steps: [
      { do: 'Onto a side', click: 'Click when they flop onto a side.',
        tip: 'Start like Roll over: from a down, lure from the nose to the shoulder until they tip over.' },
      { do: 'Head down', click: 'Click the head resting on the floor.',
        tip: 'Bring the treat low so the head goes down too.' },
      { do: 'Stay dead', click: 'Click after 2, then 5 seconds lying still.',
        tip: 'Hand the treat to their mouth while they lie there.' },
      { do: 'From standing', click: 'Click a drop to the side from standing.',
        tip: 'Cue Down, then the flop. Over a few sets, drop the Down cue.' },
      { do: 'Bang!', click: 'Click play dead on “Bang!”',
        tip: 'Finger gun, “Bang!” The dramatic stagger comes with time.' },
    ],
    fix: ['They get straight back up: treat while they’re down, then release with “Okay”.'],
  },
  {
    id: 'crawl', suit: 'moves', level: 3, emoji: '🐛', name: 'Crawl', method: 'lure', needs: ['down'],
    blurb: 'Belly low, creeping forward.',
    cue: { word: 'Crawl', signal: 'Palm down, slide it along the floor.' },
    steps: [
      { do: 'One shuffle', click: 'Click one forward shuffle while still lying down.',
        tip: 'From a down, hold a treat on the floor just in front of the nose and pull it away slowly. Click any creep forward before the rear lifts.' },
      { do: 'A few inches', click: 'Click a crawl of a few inches.',
        tip: 'If the back end pops up, go shorter and slower.' },
      { do: 'Under your legs', click: 'Click a crawl under your bent knees.',
        tip: 'Sit on the floor with your knees up to make a tunnel.' },
      { do: 'Add the word', click: 'Click a crawl after the word.',
        tip: 'Say “Crawl”.' },
    ],
    fix: ['They stand up: use a low tunnel like a coffee table or your legs.'],
  },
  {
    id: 'hoop', suit: 'moves', level: 3, emoji: '⭕', name: 'Through the hoop', method: 'lure', needs: ['jump'],
    blurb: 'Jump through a hoop, or through your arms.',
    caution: 'Same as Jump over: keep it low, and wait until growth plates close before real jumps.',
    cue: { word: 'Hoop', signal: 'Point through the hoop.' },
    steps: [
      { do: 'Walk through', click: 'Click them walking through the hoop on the floor.',
        tip: 'A hula hoop works. Hold it upright, resting on the floor, and lure them through.' },
      { do: 'Lift it', click: 'Click a hop through the hoop a few inches up.',
        tip: 'Raise it a little at a time.' },
      { do: 'No lure', click: 'Click going through when you point.',
        tip: 'Toss the treat on the far side after the click.' },
      { do: 'Add the word', click: 'Click a hoop on the word.',
        tip: 'Say “Hoop”. Later, make a hoop with your arms.' },
    ],
    fix: ['They duck under: rest the hoop on the floor again for a set or two.'],
  },
  {
    id: 'weave', suit: 'moves', level: 4, emoji: '♾️', name: 'Leg weave', method: 'lure', needs: ['middle'],
    blurb: 'Weave through your legs as you walk, in a figure 8.',
    caution: 'Take big slow steps. Small dogs are easy to trip over.',
    cue: { word: 'Weave', signal: 'Take a big step and point through.' },
    steps: [
      { do: 'Under one leg', click: 'Click them passing under one leg.',
        tip: 'Take a big step forward and lure them through the gap from the outside.' },
      { do: 'The other leg', click: 'Click a pass under the other leg.',
        tip: 'Step forward with the other foot and lure back through.' },
      { do: 'Two in a row', click: 'Click after two passes.',
        tip: 'Walk slowly. Treat after two, then three.' },
      { do: 'Empty hands', click: 'Click a weave to a pointing hand.',
        tip: 'Point through the gap instead of luring.' },
      { do: 'Add the word', click: 'Click a weave after the word.',
        tip: 'Say “Weave”.' },
    ],
    fix: ['They go round the outside: take a bigger step so the gap is obvious.'],
  },
  {
    id: 'catch', suit: 'moves', level: 1, emoji: '🥏', name: 'Catch', method: 'capture',
    blurb: 'Snatch a treat or a toy out of the air.',
    cue: { word: 'Catch' },
    steps: [
      { do: 'Easy lobs', click: 'Click a catch.',
        tip: 'Toss a soft treat in a gentle arc from about 2 ft, right at the nose. If they miss, pick it up before they do. They learn that catching is the only way to get it.' },
      { do: 'Further away', click: 'Click a catch from a few feet away.',
        tip: 'Step back a little each set.' },
      { do: 'Toys', click: 'Click a caught toy.',
        tip: 'A soft toy or a ball, thrown underhand.' },
      { do: 'Add the word', click: 'Click a catch after the word.',
        tip: 'Say “Catch” just before the toss.' },
    ],
    fix: ['The treat bounces off their face: that’s normal for a week or two. Use bigger, softer treats.'],
  },

  // Helpers & games
  {
    id: 'findit', suit: 'helpers', level: 1, emoji: '👃', name: 'Find it', method: 'capture',
    blurb: 'Sniff out hidden treats.',
    why: 'Five minutes of sniffing tires a dog out more than a long walk. Good for rainy days, anxious dogs and old dogs.',
    cue: { word: 'Find it', signal: 'Sweep your hand low.' },
    steps: [
      { do: 'Toss and say', click: 'Click as they find the tossed treat.',
        tip: 'Say “Find it!” and toss a treat on the floor a few feet away. Easy wins.' },
      { do: 'Half hidden', click: 'Click finding a half-hidden treat.',
        tip: 'Put treats behind a chair leg while they watch.' },
      { do: 'Out of sight', click: 'Click finding a treat they didn’t see you hide.',
        tip: 'Hide it while they wait in a stay, or while someone holds them.' },
      { do: 'Search the room', click: 'Click each find.',
        tip: 'Hide five treats around one room.' },
    ],
    fix: ['They give up: make the next hide easier, and say “Find it” as they get close.'],
  },
  {
    id: 'fetch', suit: 'helpers', level: 2, emoji: '🎾', name: 'Fetch', method: 'shape', needs: ['drop'],
    blurb: 'Chase it, bring it back, put it in your hand.',
    cue: { word: 'Fetch', signal: 'Point where it went.' },
    steps: [
      { do: 'The grab', click: 'Click as they grab the toy.',
        tip: 'Toss a favorite toy a few feet. Click the grab. They’ll drop it and come for the treat, which is fine for now.' },
      { do: 'Turn back', click: 'Click as they turn toward you with it.',
        tip: 'Wait a moment after the grab before you click.' },
      { do: 'Bring it close', click: 'Click when they come within arm’s reach holding it.',
        tip: 'Back away to get them to follow. Never chase them.' },
      { do: 'Into your hand', click: 'Click the toy landing in your hand.',
        tip: 'Hold your hand under their chin and cue Drop it.' },
      { do: 'Add the word', click: 'Click a full fetch after the word.',
        tip: 'Say “Fetch” as you throw.' },
    ],
    fix: ['Keep-away: run the other way, or use two toys and throw the second as they bring the first.'],
  },
  {
    id: 'whichhand', suit: 'helpers', level: 2, emoji: '✊', name: 'Which hand?', method: 'shape',
    blurb: 'Pick the fist with the treat in it.',
    cue: { word: 'Which hand?', signal: 'Hold both fists out low.' },
    steps: [
      { do: 'Sniff the fists', click: 'Click a nose on the fist with the treat.',
        tip: 'Treat in one fist, the other empty. Hold both out low. Click the right choice and open that hand.' },
      { do: 'Paw to choose', click: 'Click a paw touch on the right fist.',
        tip: 'Optional, but a paw makes a better show than a nose.' },
      { do: 'Switch behind your back', click: 'Click a right choice after you switch hands.',
        tip: 'Move the treat behind your back each time so they have to smell for it.' },
      { do: 'Add the words', click: 'Click a right answer to “Which hand?”',
        tip: 'Wrong fist? Open it to show it’s empty and try again.' },
    ],
    fix: ['They always pick the same side: switch more, and wait for a sniff at both.'],
  },
  {
    id: 'bell', suit: 'helpers', level: 2, emoji: '🔔', name: 'Ring to go out', method: 'target', needs: ['touch'],
    blurb: 'Nudge a bell on the door when they need to go out.',
    cue: { word: 'Bell', signal: 'Point at the bell.' },
    steps: [
      { do: 'Touch the bell', click: 'Click a nose bump on the bell.',
        tip: 'Hold a strap of jingle bells in front of them, like your hand for Touch.' },
      { do: 'Bell on the door', click: 'Click a ring on the door.',
        tip: 'Hang it on the door handle. Point and cue Touch.' },
      { do: 'Ring means out', click: 'Click the ring, then open the door and go out.',
        tip: 'Before every potty trip, cue a ring. The door opening is part of the reward.' },
      { do: 'Their idea', click: 'Click them ringing it with no cue.',
        tip: 'Ringing gets a potty trip and a sniff, not playtime, or you’ll be opening the door every ten minutes.' },
    ],
    fix: ['They’re scared of the noise: stuff the bells with a little cotton at first.'],
  },
  {
    id: 'chin', suit: 'helpers', level: 3, emoji: '🩺', name: 'Chin rest', method: 'shape', hold: true, needs: ['touch'],
    blurb: 'Chin in your hand, holding still, for eye drops, ear checks and nail trims.',
    why: 'The vet trick. Your dog says “go ahead” by resting their chin, and “pause” by lifting it.',
    cue: { word: 'Chin', signal: 'Cupped hand low in front of them.' },
    steps: [
      { do: 'Chin in your hand', click: 'Click the chin resting in your cupped palm.',
        tip: 'Kneel beside them with a folded towel over your palm at chin height. Lure the chin onto it from the other side if you need to.' },
      { do: 'Hold it', click: 'Click after 2, then 5, then 10 seconds.',
        tip: 'Treat while the chin stays down.' },
      { do: 'Add a touch', click: 'Click holding still while your other hand touches an ear.',
        tip: 'One touch, then click. If the chin lifts, stop touching. That’s them saying pause, and respecting it is the whole point.' },
      { do: 'Real care', click: 'Click holding still for a brush, a nail tap, or a look in the ear.',
        tip: 'Build up slowly over many short sessions.' },
    ],
    fix: ['They lift up the moment you reach: go back to a smaller movement, like lifting your hand an inch.'],
  },
  {
    id: 'leash', suit: 'helpers', level: 3, emoji: '🦮', name: 'Get your leash', method: 'shape', needs: ['fetch'],
    blurb: 'Fetch the leash when it’s time for a walk.',
    cue: { word: 'Get your leash' },
    steps: [
      { do: 'Hold the leash', click: 'Click when they take the leash handle in their mouth.',
        tip: 'Use a spare leash with a soft handle. Hold it out, and click interest, then a grab.' },
      { do: 'Hand it over', click: 'Click the leash dropped in your hand.',
        tip: 'Cue Drop it with your hand under their chin.' },
      { do: 'From the hook', click: 'Click a grab from where it hangs.',
        tip: 'Hang it low where they can reach it, and point.' },
      { do: 'Bring it over', click: 'Click them bringing it from across the room.',
        tip: 'Say “Get your leash”. Then go for a walk. Best reward there is.' },
    ],
    fix: ['They chew it: use an old leash for practice, and click sooner.'],
  },
  {
    id: 'closedoor', suit: 'helpers', level: 3, emoji: '🚪', name: 'Close the door', method: 'target', needs: ['pawtarget'],
    blurb: 'Push a door shut with a paw.',
    caution: 'Pick doors that close softly, and keep tails and toes clear.',
    cue: { word: 'Close it', signal: 'Point at the door.' },
    steps: [
      { do: 'Note on the door', click: 'Click a paw on the sticky note.',
        tip: 'Stick the note at paw height on a cabinet door or a light inside door that’s nearly shut.' },
      { do: 'Push it', click: 'Click a push that moves the door.',
        tip: 'Wait for a firmer press.' },
      { do: 'All the way', click: 'Click when the door clicks shut.',
        tip: 'Start with it almost closed and open it wider each set.' },
      { do: 'Lose the note', click: 'Click a close with a smaller note, then none.',
        tip: 'Cut the note in half each set.' },
    ],
    fix: ['They use their nose: that works too, if you’re happy with nose prints.'],
  },
  {
    id: 'shell', suit: 'helpers', level: 3, emoji: '🥤', name: 'Shell game', method: 'shape', needs: ['whichhand'],
    blurb: 'Find the treat under one of three cups.',
    cue: { word: 'Which one?', signal: 'Gesture at the cups.' },
    steps: [
      { do: 'One cup', click: 'Click a nose or paw on the cup with the treat.',
        tip: 'Put a treat under a plastic cup while they watch. Click the touch, then lift the cup.' },
      { do: 'Two cups', click: 'Click a touch on the right cup.',
        tip: 'Wrong cup: lift it to show it’s empty, and start again.' },
      { do: 'Three cups', click: 'Click the right cup of three.',
        tip: 'Go slowly and let them sniff each one.' },
      { do: 'Shuffle', click: 'Click the right cup after a shuffle.',
        tip: 'Slide the cups around slowly. Their nose knows.' },
    ],
    fix: ['They knock all the cups over: that’s allowed. Use heavier cups, or just click the first touch.'],
  },
  {
    id: 'hideseek', suit: 'helpers', level: 3, emoji: '🔍', name: 'Hide and seek', method: 'capture', needs: ['stay', 'come'],
    blurb: 'You hide, they find you.',
    why: 'Recall practice disguised as a game. Kids love it.',
    cue: { word: 'Come find me!' },
    steps: [
      { do: 'Easy hide', click: 'Click as they find you.',
        tip: 'Ask for a stay, or have someone hold them. Step just behind a door and call “Come find me!”' },
      { do: 'Other rooms', click: 'Click them finding you in another room.',
        tip: 'Call once and then stay quiet.' },
      { do: 'Harder spots', click: 'Click a find behind the shower curtain.',
        tip: 'Stay quiet for longer once they’re good at it.' },
      { do: 'Whole house', click: 'Click a find from anywhere.',
        tip: 'Take turns hiding. Big party when they find you.' },
    ],
    fix: ['They wander off: go back to hiding in plain sight, and call again.'],
  },
  {
    id: 'toyname', suit: 'helpers', level: 4, emoji: '🧸', name: 'Get it by name', method: 'shape', needs: ['fetch'],
    blurb: 'Bring the right toy when you ask for it by name.',
    cue: { word: 'Get Bunny' },
    steps: [
      { do: 'One toy, one name', click: 'Click a pickup of the named toy.',
        tip: 'Pick a toy and a name, say “Bunny”. Say the name every time they grab it. Only that toy for now.' },
      { do: 'Two on the floor', click: 'Click them picking the right one of two.',
        tip: 'Put Bunny next to a toy they don’t care about. Say “Get Bunny”. Wrong toy: no click, reset.' },
      { do: 'Swap places', click: 'Click the right toy wherever it sits.',
        tip: 'Move the toys around so they learn the name, not the spot.' },
      { do: 'A second name', click: 'Click the right toy for the second name.',
        tip: 'Teach the next toy alone, then mix. Some dogs learn dozens.' },
    ],
    fix: ['They always grab the same one: go back to one toy, and make the other toy boring.'],
  },
  {
    id: 'tidy', suit: 'helpers', level: 4, emoji: '🧺', name: 'Put your toys away', method: 'shape', needs: ['fetch'],
    blurb: 'Pick up toys and drop them in the basket.',
    cue: { word: 'Tidy up', signal: 'Point from the toy to the basket.' },
    steps: [
      { do: 'Drop into the basket', click: 'Click the toy falling into the basket.',
        tip: 'Hold a low, wide basket under their chin while they hold a toy, and cue Drop it.' },
      { do: 'Basket on the floor', click: 'Click a drop into the basket on the floor.',
        tip: 'Hold your hand over the basket to guide them.' },
      { do: 'Pick up, then drop', click: 'Click a toy picked up and dropped in.',
        tip: 'Start with a toy right next to the basket.' },
      { do: 'More toys', click: 'Click after two, then three toys go in.',
        tip: 'Say “Tidy up” and point to the toys.' },
    ],
    fix: ['They drop it next to the basket: use a bigger basket, then a smaller one later.'],
  },
];

export const TRICKS = T;

// Card 0 is the start card; the four suits follow in order, numbered 1–48.
const SUIT_ORDER = ['start', ...SUITS.map(s => s.id)];
TRICKS.sort((a, b) => SUIT_ORDER.indexOf(a.suit) - SUIT_ORDER.indexOf(b.suit) || a.level - b.level);
TRICKS.forEach((t, i) => { t.n = i; t.needs = t.needs || []; });

export const BY_ID = Object.fromEntries(TRICKS.map(t => [t.id, t]));

export function suitOf(t) {
  return SUITS.find(s => s.id === t.suit) || { id: 'start', name: 'Start here', short: 'Start' };
}
